## Working with APIs

In [1]:
import requests

In [2]:
URL = "https://stephen-king-api.onrender.com/api/books"
res = requests.get(URL)

In [3]:
json_data = res.json()

In [4]:
import pandas as pd

df = pd.json_normalize(json_data["data"])

In [5]:
df

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
58,59,2018,The Outsider,the-outsider,Scribner,978-1-50118-098-9,576,"[First novel in the Holly Gibney Series, Runne...",2023-11-13T23:48:55.165Z,"[{'name': 'The Outsider (Creature)', 'url': 'h..."
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]

In [6]:
df = df[['id','Title','Year','ISBN']]

In [7]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

## Web Scrapping

- requests
- beautifulSoup
- Selenium

In [19]:
# basic get requests

import requests

URL = "https://www.scrapethissite.com/pages/simple"
res = requests.get(URL)

In [20]:
res

In [21]:
if res.status_code == 200:
    print(res.text)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="countries">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>
                            <strong>Population:</strong> <span class="country-population">84000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>
                            <strong>Population:</strong> <span class="country-population">4975593</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>
                            <strong>Population:</strong> <span class="country-population">29121286</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>
                            <strong>Population:</strong> <span class="country-population">86754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>
                            <strong>Population:</strong> <span class="country-population">13254</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>
                            <strong>Population:</strong> <span class="country-population">2986952</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>
                            <strong>Population:</strong> <span class="country-population">2968000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>
                            <strong>Population:</strong> <span class="country-population">13068161</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">None</span><br>
                            <strong>Population:</strong> <span class="country-population">0</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>
                            <strong>Population:</strong> <span class="country-population">41343201</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>
                            <strong>Population:</strong> <span class="country-population">57881</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>
                            <strong>Population:</strong> <span class="country-population">8205000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
                            <strong>Population:</strong> <span class="country-population">21515754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>
                            <strong>Population:</strong> <span class="country-population">71566</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>
                            <strong>Population:</strong> <span class="country-population">26711</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>
                            <strong>Population:</strong> <span class="country-population">8303512</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>
                            <strong>Population:</strong> <span class="country-population">4590000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>
                            <strong>Population:</strong> <span class="country-population">285653</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br>
                            <strong>Population:</strong> <span class="country-population">156118464</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Brussels</span><br>
                            <strong>Population:</strong> <span class="country-population">10403000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br>

In [22]:
if res.status_code == 200:
    print(res.content)

b'<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>\n    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">\n\n    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">\n    <link href=\'https://fonts.googleapis.com/css?family=Lato:400,700\' rel=\'stylesheet\' type=\'text/css\'>\n    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">\n\n    \n<meta name="robots" content="noindex">\n<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">\n\n\n  </head>\n\n  <body>\n    <nav id="site-nav">\n            <div class="container">\n                <div class="col-md-12">\n                    <ul class="nav nav-tabs">\n                        <li id="nav-homepage">\n                            <a href="/" class="nav-link hidden-sm hidden-xs">\n                                <img src="/static/images/scraper-icon.png" id="nav-logo">\n                                Scrape This Site\n                            </a>\n                        </li>\n                        <li id="nav-sandbox">\n                            <a href="/pages/" class="nav-link">\n                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>\n                                Sandbox\n                            </a>\n                        </li>\n                        <li id="nav-lessons">\n                            <a href="/lessons/" class="nav-link">\n                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>\n                                Lessons\n                            </a>\n                        </li>\n                        <li id="nav-faq">\n                            <a href="/faq/" class="nav-link">\n                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>\n                                FAQ\n                            </a>\n                        </li>\n                        \n                        <li id="nav-login" class="pull-right">\n                            <a href="/login/" class="nav-link">\n                                Login\n                            </a>\n                        </li>\n                        \n                    </ul>\n                </div>\n            </div>\n        </nav>\n\n        <script type="text/javascript">\n            var path = document.location.pathname;\n            var tab = undefined;\n            if (path === "/"){\n                tab = document.querySelector("#nav-homepage");\n            } else if (path.indexOf("/faq/") === 0){\n                tab = document.querySelector("#nav-faq");\n            } else if (path.indexOf("/lessons/") === 0){\n                tab = document.querySelector("#nav-lessons");\n            } else if (path.indexOf("/pages/") === 0) {\n                tab = document.querySelector("#nav-sandbox");\n            } else if (path.indexOf("/login/") === 0) {\n                tab = document.querySelector("#nav-login");\n            }\n            tab.classList.add("active")\n        </script>\n\n    \n\n    <div id="page">\n\n        <section id="countries">\n            <div class="container">\n\n                <div class="row">\n                    <div class="col-md-12">\n                        <h1>\n                            Countries of the World: A Simple Example\n                            <small>250 items</small>\n                        </h1>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-12">\n                        <p class="lead">\n                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.\n                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.\n                        </p>\n                        <hr />\n                    </div>\n                </div>\n                <div class="row">\n                    <div class="col-md-6">\n                        <p>\n                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.\n                        </p>\n                        <hr />\n                    </div>\n                    <div class="col-md-6 text-right">\n                        <p>\n                            \n                                Data via\n                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>\n                            \n                        </p>\n                        <hr />\n                    </div>\n                </div>\n\n                <div class="row">\n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ad"></i>\n                            Andorra\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>\n                            <strong>Population:</strong> <span class="country-population">84000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ae"></i>\n                            United Arab Emirates\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>\n                            <strong>Population:</strong> <span class="country-population">4975593</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-af"></i>\n                            Afghanistan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>\n                            <strong>Population:</strong> <span class="country-population">29121286</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ag"></i>\n                            Antigua and Barbuda\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>\n                            <strong>Population:</strong> <span class="country-population">86754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ai"></i>\n                            Anguilla\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>\n                            <strong>Population:</strong> <span class="country-population">13254</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-al"></i>\n                            Albania\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>\n                            <strong>Population:</strong> <span class="country-population">2986952</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-am"></i>\n                            Armenia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>\n                            <strong>Population:</strong> <span class="country-population">2968000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ao"></i>\n                            Angola\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>\n                            <strong>Population:</strong> <span class="country-population">13068161</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aq"></i>\n                            Antarctica\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">None</span><br>\n                            <strong>Population:</strong> <span class="country-population">0</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ar"></i>\n                            Argentina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>\n                            <strong>Population:</strong> <span class="country-population">41343201</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-as"></i>\n                            American Samoa\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>\n                            <strong>Population:</strong> <span class="country-population">57881</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-at"></i>\n                            Austria\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>\n                            <strong>Population:</strong> <span class="country-population">8205000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-au"></i>\n                            Australia\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>\n                            <strong>Population:</strong> <span class="country-population">21515754</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-aw"></i>\n                            Aruba\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>\n                            <strong>Population:</strong> <span class="country-population">71566</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ax"></i>\n                            \xc3\x85land\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>\n                            <strong>Population:</strong> <span class="country-population">26711</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-az"></i>\n                            Azerbaijan\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>\n                            <strong>Population:</strong> <span class="country-population">8303512</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-ba"></i>\n                            Bosnia and Herzegovina\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>\n                            <strong>Population:</strong> <span class="country-population">4590000</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                    \n                    \n                    <div class="col-md-4 country">\n                        <h3 class="country-name">\n                            <i class="flag-icon flag-icon-bb"></i>\n                            Barbados\n                        </h3>\n                        <div class="country-info">\n                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>\n                            <strong>Population:</strong> <span class="country-population">285653</span><br>\n                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>\n                        </div>\n                    </div><!--.col-->\n                    \n                </div><!--.row-->\n                <div class="row">\n                    \n                    \n                    \n                    <div class="col-

In [23]:
if res.status_code == 200:
    print(res.headers)

{'Date': 'Fri, 06 Feb 2026 05:28:29 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=wPOyoTrhJPlweZkde%2BHivKrwVgp5UrEKmxn0PV69%2BBs%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1770355709"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=wPOyoTrhJPlweZkde%2BHivKrwVgp5UrEKmxn0PV69%2BBs%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1770355709"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9c983e8dbd431f9f-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

In [26]:
with open("scraped_data/data1.html", "w", encoding="utf-8") as f:
    f.write(res.text)

Beautiful soup

In [27]:
from bs4 import BeautifulSoup

In [28]:
with open("scraped_data/data1.html","r") as f:
    html_content =  f.read()

soup = BeautifulSoup(html_content,"lxml")

In [29]:
soup

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
<link href="/static/images/scraper-icon.png" rel="icon" type="image/png"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping." name="description"/>
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet" type="text/css"/>
<link href="/static/css/styles.css" rel="stylesheet" type="text/css"/>
<meta content="noindex" name="robots"/>
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet"/>
</head>
<body>
<nav id="site-nav">
<div class="container">
<div class="col-md-12">
<ul class="nav nav-tabs">
<li id="nav-homepage">
<a class="nav-link hidden-sm hidden-xs" href="/">
<img id="nav-logo" src="/static/images/scraper-icon.png"/>
                                Scrape This Site
                            </a>
</li>
<li id="nav-sandbox">
<a class="nav-link" href="/pages/">
<i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
</li>
<li id="nav-lessons">
<a class="nav-link" href="/lessons/">
<i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
</li>
<li id="nav-faq">
<a class="nav-link" href="/faq/">
<i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
</li>
<li class="pull-right" id="nav-login">
<a class="nav-link" href="/login/">
                                Login
                            </a>
</li>
</ul>
</div>
</div>
</nav>
<script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>
<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Ã…land
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint BarthÃ©lemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">BrasÃ­lia</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island

Methods of BeautifulSoup ->
- find()
- find_all()
- find_parent()
- find_next()
- find_previous()

css selctors -
- select()
- select_one()

attributes - 
- get()
- .attrs

In [32]:
soup.find("h3")

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [33]:
all_h3 = soup.find_all("h3")

for h3 in all_h3:
    print(h3.get_text())

                            Andorra



                            United Arab Emirates



                            Afghanistan



                            Antigua and Barbuda



                            Anguilla



                            Albania



                            Armenia



                            Angola



                            Antarctica



                            Argentina



                            American Samoa



                            Austria



                            Australia



                            Aruba



                            Ã…land



                            Azerbaijan



                            Bosnia and Herzegovina



                            Barbados



                            Bangladesh



                            Belgium



                            Burkina Faso



                            Bulgaria



                            Bahrain



                            Burundi



                            Benin



                            Saint BarthÃ©lemy



                            Bermuda



                            Brunei



                            Bolivia



                            Bonaire



                            Brazil



                            Bahamas



                            Bhutan



                            Bouvet Island



                            Botswana



                            Belarus



                            Belize



                            Canada



                            Cocos [Keeling] Islands



                            Democratic Republic of the Congo



                            Central African Republic



                            Republic of the Congo



                            Switzerland



                            Ivory Coast



                            Cook Islands



                            Chile



                            Cameroon



                            China



                            Colombia



                            Costa Rica



                            Cuba



                            Cape Verde



                            Curacao



                            Christmas Island



                            Cyprus



                            Czech Republic



                            Germany



                            Djibouti



                            Denmark



                            Dominica



                            Dominican Republic



                            Algeria



                            Ecuador



                            Estonia



                            Egypt



                            Western Sahara



                            Eritrea



                            Spain



                            Ethiopia



                            Finland



                            Fiji



                            Falkland Islands



                            Micronesia



                            Faroe Islands



                            France



                            Gabon



                            United Kingdom



                            Grenada



                            Georgia



                            French Guiana



                            Guernsey



                            Ghana



                            Gibraltar



                            Greenland



                            Gambia



                            Guinea



                            Guadeloupe



                            Equatorial Guinea



                            Greece



                            South Georgia and the South Sandwich Islands



                            Guatemala



                            Guam



                            Guinea-Bissau



                            Guyana



                            Hong Kong



                            Heard Island and McDonald Islands



                            Honduras



                            Croatia



                            Haiti



                            Hungary



                            Indonesia



                            Ireland



                            Israel



                            Isle of Man



                            India



                            British Indian Ocean Territory



                            Iraq



                            Iran



                            Iceland



                            Italy



                            Jersey



                            Jamaica



                            Jordan



                            Japan



                            Kenya



                            Kyrgyzstan



                            Cambodia



                            Kiribati



                            Comoros



                            Saint Kitts and Nevis



                            North Korea



                            South Korea



                            Kuwait



                            Cayman Islands



                            Kazakhstan



                            Laos



                            Lebanon



                            Saint Lucia



                            Liechtenstein



                            Sri Lanka



                            Liberia



                            Lesotho



                            Lithuania



                            Luxembourg



                            Latvia



                            Libya



                            Morocco



                            Monaco



                            Moldova



                            Montenegro



                            Saint Martin



                            Madagascar



                            Marshall Islands



                            Macedonia



                            Mali



                            Myanmar [Burma]



                            Mongolia



                            Macao



                            Northern Mariana Islands



                            Martinique



                            Mauritania



                            Montserrat



                            Malta



                            Mauritius



                            Maldives



                            Malawi



                            Mexico



                            Malaysia



                            Mozambique



                            Namibia



                            New Caledonia



                            Niger



                            Norfolk Island



                            Nigeria



                            Nicaragua



                            Netherlands



                            Norway



                            Nepal



                            Nauru



                            Niue



                            New Zealand



                            Oman



                            Panama



                            Peru



                            French Polynesia



                            Papua New Guinea



                            Philippines



                            Pakistan



                            Poland



                            Saint Pierre and Miquelon



                            Pitcairn Islands



                            Puerto Rico



                            Palestine



                            Portugal



                            Palau



                            Paraguay



                            Qatar



                            RÃ©union



                            Romania



                            Serbia



                            Russia



                            Rwanda



                            Saudi Arabia



                            Solomon Islands



                            Seychelles



                            Sudan



                            Sweden



                            Singapore



                            Saint Helena



                            Slovenia



                            Svalbard and Jan Mayen



                            Slovakia



                            Sierra Leone



                            San Marino



                            Senegal



                            Somalia



                            Suriname



                            South Sudan



                            SÃ£o TomÃ© and PrÃ­ncipe



                            El Salvador



                            Sint Maarten



                            Syria



                            Swaziland



                            Turks and Caicos Islands



                            Chad



                            French Southern Territories



                            Togo



                            Thailand



                            Tajikistan



                            Tokelau



                            East Timor



                            Turkmenistan



                            Tunisia



                            Tonga



                            Turkey



                            Trinidad and Tobago



                            Tuvalu



                            Taiwan



                            Tanzania



                            Ukraine



                            Uganda



                            U.S. Minor Outlying Islands



                            United States



                            Uruguay



                            Uzbekistan



                            Vatican City



                            Saint Vincent and the Grenadines



                            Venezuela



                            British Virgin Islands



                            U.S. Virgin Islands



                            Vietnam



                            Vanuatu



                            Wallis and Futuna



                            Samoa



                            Kosovo



                            Yemen



                            Mayotte



                            South Africa



                            Zambia



                            Zimbabwe

In [40]:
all_countries = []

for h3 in all_h3:
    name = h3.get_text(strip = True)

    population = h3.find_next("div").select("span.country-population")[0].get_text()
    print(population)
    print(h3.attrs)

    all_countries.append([name,population])

84000
{'class': ['country-name']}
4975593
{'class': ['country-name']}
29121286
{'class': ['country-name']}
86754
{'class': ['country-name']}
13254
{'class': ['country-name']}
2986952
{'class': ['country-name']}
2968000
{'class': ['country-name']}
13068161
{'class': ['country-name']}
0
{'class': ['country-name']}
41343201
{'class': ['country-name']}
57881
{'class': ['country-name']}
8205000
{'class': ['country-name']}
21515754
{'class': ['country-name']}
71566
{'class': ['country-name']}
26711
{'class': ['country-name']}
8303512
{'class': ['country-name']}
4590000
{'class': ['country-name']}
285653
{'class': ['country-name']}
156118464
{'class': ['country-name']}
10403000
{'class': ['country-name']}
16241811
{'class': ['country-name']}
7148785
{'class': ['country-name']}
738004
{'class': ['country-name']}
9863117
{'class': ['country-name']}
9056010
{'class': ['country-name']}
8450
{'class': ['country-name']}
65365
{'class': ['country-name']}
395027
{'class': ['country-name']}
9947418
{'class': ['country-name']}
18012
{'class': ['country-name']}
201103330
{'class': ['country-name']}
301790
{'class': ['country-name']}
699847
{'class': ['country-name']}
0
{'class': ['country-name']}
2029307
{'class': ['country-name']}
9685000
{'class': ['country-name']}
314522
{'class': ['country-name']}
33679000
{'class': ['country-name']}
628
{'class': ['country-name']}
70916439
{'class': ['country-name']}
4844927
{'class': ['country-name']}
3039126
{'class': ['country-name']}
7581000
{'class': ['country-name']}
21058798
{'class': ['country-name']}
21388
{'class': ['country-name']}
16746491
{'class': ['country-name']}
19294149
{'class': ['country-name']}
1330044000
{'class': ['country-name']}
47790000
{'class': ['country-name']}
4516220
{'class': ['country-name']}
11423000
{'class': ['country-name']}
508659
{'class': ['country-name']}
141766
{'class': ['country-name']}
1500
{'class': ['country-name']}
1102677
{'class': ['country-name']}
10476000
{'class': ['country-name']}
81802257
{'class': ['country-name']}
740528
{'class': ['country-name']}
5484000
{'class': ['country-name']}
72813
{'class': ['country-name']}
9823821
{'class': ['country-name']}
34586184
{'class': ['country-name']}
14790608
{'class': ['country-name']}
1291170
{'class': ['country-name']}
80471869
{'class': ['country-name']}
273008
{'class': ['country-name']}
5792984
{'class': ['country-name']}
46505963
{'class': ['country-name']}
88013491
{'class': ['country-name']}
5244000
{'class': ['country-name']}
875983
{'class': ['country-name']}
2638
{'class': ['country-name']}
107708
{'class': ['country-name']}
48228
{'class': ['country-name']}
64768389
{'class': ['country-name']}
1545255
{'class': ['country-name']}
62348447
{'class': ['country-name']}
107818
{'class': ['country-name']}
4630000
{'class': ['country-name']}
195506
{'class': ['country-name']}
65228
{'class': ['country-name']}
24339838
{'class': ['country-name']}
27884
{'class': ['country-name']}
56375
{'class': ['country-name']}
1593256
{'class': ['country-name']}
10324025
{'class': ['country-name']}
443000
{'class': ['country-name']}
1014999
{'class': ['country-name']}
11000000
{'class': ['country-name']}
30
{'class': ['country-name']}
13550440
{'class': ['country-name']}
159358
{'class': ['country-name']}
1565126
{'class': ['country-name']}
748486
{'class': ['country-name']}
6898686
{'class': ['country-name']}
0
{'class': ['country-name']}
7989415
{'class': ['country-name']}
4491000
{'class': ['country-name']}
9648924
{'class': ['country-name']}
9982000
{'class': ['country-name']}
242968342
{'class': ['country-name']}
4622917
{'class': ['country-name']}
7353985
{'class': ['country-name']}
75049
{'class': ['country-name']}
1173108018
{'class': ['country-name']}
4000
{'class': ['country-name']}
29671605
{'class': ['country-name']}
76923300
{'class': ['country-name']}
308910
{'class': ['country-name']}
60340328
{'class': ['country-name']}
90812
{'class': ['country-name']}
2847232
{'class': ['country-name']}
6407085
{'class': ['country-name']}
127288000
{'class': ['country-name']}
40046566
{'class': ['country-name']}
5776500
{'class': ['country-name']}
14453680
{'class': ['country-name']}
92533
{'class': ['country-name']}
773407
{'class': ['country-name']}
51134
{'class': ['country-name']}
22912177
{'class': ['country-name']}
48422644
{'class': ['country-name']}
2789132
{'class': ['country-name']}
44270
{'class': ['country-name']}
15340000
{'class': ['country-name']}
6368162
{'class': ['country-name']}
4125247
{'class': ['country-name']}
160922
{'class': ['country-name']}
35000
{'class': ['country-name']}
21513990
{'class': ['country-name']}
3685076
{'class': ['country-name']}
1919552
{'class': ['country-name']}
2944459
{'class': ['country-name']}
497538
{'class': ['country-name']}
2217969
{'class': ['country-name']}
6461454
{'class': ['country-name']}
31627428
{'class': ['country-name']}
32965
{'class': ['country-name']}
4324000
{'class': ['country-name']}
666730
{'class': ['country-name']}
35925
{'class': ['country-name']}
21281844
{'class': ['country-name']}
65859
{'class': ['country-name']}
2062294
{'class': ['country-name']}
13796354
{'class': ['country-name']}
53414374
{'class': ['country-name']}
3086918
{'class': ['country-name']}
449198
{'class': ['country-name']}
53883
{'class': ['country-name']}
432900
{'class': ['country-name']}
3205060
{'class': ['country-name']}
9341
{'class': ['country-name']}
403000
{'class': ['country-name']}
1294104
{'class': ['country-name']}
395650
{'class': ['country-name']}
15447500
{'class': ['country-name']}
112468855
{'class': ['country-name']}
28274729
{'class': ['country-name']}
22061451
{'class': ['country-name']}
2128471
{'class': ['country-name']}
216494
{'class': ['country-name']}
15878271
{'class': ['country-name']}
1828
{'class': ['country-name']}
154000000
{'class': ['country-name']}
5995928
{'class': ['country-name']}
16645000
{'class': ['country-name']}
5009150
{'class': ['country-name']}
28951852
{'class': ['country-name']}
10065
{'class': ['country-name']}
2166
{'class': ['country-name']}
4252277
{'class': ['country-name']}
2967717
{'class': ['country-name']}
3410676
{'class': ['country-name']}
29907003
{'class': ['country-name']}
270485
{'class': ['country-name']}
6064515
{'class': ['country-name']}
99900177
{'class': ['country-name']}
184404791
{'class': ['country-name']}
38500000
{'class': ['country-name']}
7012
{'class': ['country-name']}
46
{'class': ['country-name']}
3916632
{'class': ['country-name']}
3800000
{'class': ['country-name']}
10676000
{'class': ['country-name']}
19907
{'class': ['country-name']}
6375830
{'class': ['country-name']}
840926
{'class': ['country-name']}
776948
{'class': ['country-name']}
21959278
{'class': ['country-name']}
7344847
{'class': ['country-name']}
140702000
{'class': ['country-name']}
11055976
{'class': ['country-name']}
25731776
{'class': ['country-name']}
559198
{'class': ['country-name']}
88340
{'class': ['country-name']}
35000000
{'class': ['country-name']}
9828655
{'class': ['country-name']}
4701069
{'class': ['country-name']}
7460
{'class': ['country-name']}
2007000
{'class': ['country-name']}
2550
{'class': ['country-name']}
5455000
{'class': ['country-name']}
5245695
{'class': ['country-name']}
31477
{'class': ['country-name']}
12323252
{'class': ['country-name']}
10112453
{'class': ['country-name']}
492829
{'class': ['country-name']}
8260490
{'class': ['country-name']}
175808
{'class': ['country-name']}
6052064
{'class': ['country-name']}
37429
{'class': ['country-name']}
22198110
{'class': ['country-name']}
1354051
{'class': ['country-name']}
20556
{'class': ['country-name']}
10543464
{'class': ['country-name']}
140
{'class': ['country-name']}
6587239
{'class': ['country-name']}
67089500
{'class': ['country-name']}
7487489
{'class': ['country-name']}
1466
{'class': ['country-name']}
1154625
{'class': ['country-name']}
4940916
{'class': ['country-name']}
10589025
{'class': ['country-name']}
122580
{'class': ['country-name']}
77804122
{'class': ['country-name']}
1228691
{'class': ['country-name']}
10472
{'class': ['country-name']}
22894384
{'class': ['country-name']}
41892895
{'class': ['country-name']}
45415596
{'class': ['country-name']}
33398682
{'class': ['country-name']}
0
{'class': ['country-name']}
310232863
{'class': ['country-name']}
3477000
{'class': ['country-name']}
27865738
{'class': ['country-name']}
921
{'class': ['country-name']}
104217
{'class': ['country-name']}
27223228
{'class': ['country-name']}
21730
{'class': ['country-name']}
108708
{'class': ['country-name']}
89571130
{'class': ['country-name']}
221552
{'class': ['country-name']}
16025
{'class': ['country-name']}
192001
{'class': ['country-name']}
1800000
{'class': ['country-name']}
23495361
{'class': ['country-name']}
159042
{'class': ['country-name']}
49000000
{'class': ['country-name']}
13460305
{'class': ['country-name']}
11651858
{'class': ['country-name']}

In [41]:
all_countries

[['Andorra', '84000'],
 ['United Arab Emirates', '4975593'],
 ['Afghanistan', '29121286'],
 ['Antigua and Barbuda', '86754'],
 ['Anguilla', '13254'],
 ['Albania', '2986952'],
 ['Armenia', '2968000'],
 ['Angola', '13068161'],
 ['Antarctica', '0'],
 ['Argentina', '41343201'],
 ['American Samoa', '57881'],
 ['Austria', '8205000'],
 ['Australia', '21515754'],
 ['Aruba', '71566'],
 ['Ã…land', '26711'],
 ['Azerbaijan', '8303512'],
 ['Bosnia and Herzegovina', '4590000'],
 ['Barbados', '285653'],
 ['Bangladesh', '156118464'],
 ['Belgium', '10403000'],
 ['Burkina Faso', '16241811'],
 ['Bulgaria', '7148785'],
 ['Bahrain', '738004'],
 ['Burundi', '9863117'],
 ['Benin', '9056010'],
 ['Saint BarthÃ©lemy', '8450'],
 ['Bermuda', '65365'],
 ['Brunei', '395027'],
 ['Bolivia', '9947418'],
 ['Bonaire', '18012'],
 ['Brazil', '201103330'],
 ['Bahamas', '301790'],
 ['Bhutan', '699847'],
 ['Bouvet Island', '0'],
 ['Botswana', '2029307'],
 ['Belarus', '9685000'],
 ['Belize', '314522'],
 ['Canada', '33679000'],
 ['Cocos [Keeling] Islands', '628'],
 ['Democratic Republic of the Congo', '70916439'],
 ['Central African Republic', '4844927'],
 ['Republic of the Congo', '3039126'],
 ['Switzerland', '7581000'],
 ['Ivory Coast', '21058798'],
 ['Cook Islands', '21388'],
 ['Chile', '16746491'],
 ['Cameroon', '19294149'],
 ['China', '1330044000'],
 ['Colombia', '47790000'],
 ['Costa Rica', '4516220'],
 ['Cuba', '11423000'],
 ['Cape Verde', '508659'],
 ['Curacao', '141766'],
 ['Christmas Island', '1500'],
 ['Cyprus', '1102677'],
 ['Czech Republic', '10476000'],
 ['Germany', '81802257'],
 ['Djibouti', '740528'],
 ['Denmark', '5484000'],
 ['Dominica', '72813'],
 ['Dominican Republic', '9823821'],
 ['Algeria', '34586184'],
 ['Ecuador', '14790608'],
 ['Estonia', '1291170'],
 ['Egypt', '80471869'],
 ['Western Sahara', '273008'],
 ['Eritrea', '5792984'],
 ['Spain', '46505963'],
 ['Ethiopia', '88013491'],
 ['Finland', '5244000'],
 ['Fiji', '875983'],
 ['Falkland Islands', '2638'],
 ['Micronesia', '107708'],
 ['Faroe Islands', '48228'],
 ['France', '64768389'],
 ['Gabon', '1545255'],
 ['United Kingdom', '62348447'],
 ['Grenada', '107818'],
 ['Georgia', '4630000'],
 ['French Guiana', '195506'],
 ['Guernsey', '65228'],
 ['Ghana', '24339838'],
 ['Gibraltar', '27884'],
 ['Greenland', '56375'],
 ['Gambia', '1593256'],
 ['Guinea', '10324025'],
 ['Guadeloupe', '443000'],
 ['Equatorial Guinea', '1014999'],
 ['Greece', '11000000'],
 ['South Georgia and the South Sandwich Islands', '30'],
 ['Guatemala', '13550440'],
 ['Guam', '159358'],
 ['Guinea-Bissau', '1565126'],
 ['Guyana', '748486'],
 ['Hong Kong', '6898686'],
 ['Heard Island and McDonald Islands', '0'],
 ['Honduras', '7989415'],
 ['Croatia', '4491000'],
 ['Haiti', '9648924'],
 ['Hungary', '9982000'],
 ['Indonesia', '242968342'],
 ['Ireland', '4622917'],
 ['Israel', '7353985'],
 ['Isle of Man', '75049'],
 ['India', '1173108018'],
 ['British Indian Ocean Territory', '4000'],
 ['Iraq', '29671605'],
 ['Iran', '76923300'],
 ['Iceland', '308910'],
 ['Italy', '60340328'],
 ['Jersey', '90812'],
 ['Jamaica', '2847232'],
 ['Jordan', '6407085'],
 ['Japan', '127288000'],
 ['Kenya', '40046566'],
 ['Kyrgyzstan', '5776500'],
 ['Cambodia', '14453680'],
 ['Kiribati', '92533'],
 ['Comoros', '773407'],
 ['Saint Kitts and Nevis', '51134'],
 ['North Korea', '22912177'],
 ['South Korea', '48422644'],
 ['Kuwait', '2789132'],
 ['Cayman Islands', '44270'],
 ['Kazakhstan', '15340000'],
 ['Laos', '6368162'],
 ['Lebanon', '4125247'],
 ['Saint Lucia', '160922'],
 ['Liechtenstein', '35000'],
 ['Sri Lanka', '21513990'],
 ['Liberia', '3685076'],
 ['Lesotho', '1919552'],
 ['Lithuania', '2944459'],
 ['Luxembourg', '497538'],
 ['Latvia', '2217969'],
 ['Libya', '6461454'],
 ['Morocco', '31627428'],
 ['Monaco', '32965'],
 ['Moldova', '4324000'],
 ['Montenegro', '666730'],
 ['Saint Martin', '35925'],
 ['Madagascar', '21281844'],
 ['Marshall Islands', '65859'],
 ['Macedonia', '2062294'],
 ['Mali', '13796354'],
 ['Myanmar [Burma]', '53414374'],
 ['Mongolia', '3086918'],
 ['Macao', '449198'],
 ['Northern Mariana Islands', '53883'],
 ['Martinique', '432900'],
 ['Mauritania', '3205060'],
 ['Montserrat', '9341'],
 ['Malta', '403000'],
 ['Mauritius', '1294104'],
 ['Maldives', '395650'],
 ['Malawi', '15447500'],
 ['Mexico', '112468855'],
 ['Malaysia', '28274729'],
 ['Mozambique', '22061451'],
 ['Namibia', '2128471'],
 ['New Caledonia', '216494'],
 ['Niger', '15878271'],
 ['Norfolk Island', '1828'],
 ['Nigeria', '154000000'],
 ['Nicaragua', '5995928'],
 ['Netherlands', '16645000'],
 ['Norway', '5009150'],
 ['Nepal', '28951852'],
 ['Nauru', '10065'],
 ['Niue', '2166'],
 ['New Zealand', '4252277'],
 ['Oman', '2967717'],
 ['Panama', '3410676'],
 ['Peru', '29907003'],
 ['French Polynesia', '270485'],
 ['Papua New Guinea', '6064515'],
 ['Philippines', '99900177'],
 ['Pakistan', '184404791'],
 ['Poland', '38500000'],
 ['Saint Pierre and Miquelon', '7012'],
 ['Pitcairn Islands', '46'],
 ['Puerto Rico', '3916632'],
 ['Palestine', '3800000'],
 ['Portugal', '10676000'],
 ['Palau', '19907'],
 ['Paraguay', '6375830'],
 ['Qatar', '840926'],
 ['RÃ©union', '776948'],
 ['Romania', '21959278'],
 ['Serbia', '7344847'],
 ['Russia', '140702000'],
 ['Rwanda', '11055976'],
 ['Saudi Arabia', '25731776'],
 ['Solomon Islands', '559198'],
 ['Seychelles', '88340'],
 ['Sudan', '35000000'],
 ['Sweden', '9828655'],
 ['Singapore', '4701069'],
 ['Saint Helena', '7460'],
 ['Slovenia', '2007000'],
 ['Svalbard and Jan Mayen', '2550'],
 ['Slovakia', '5455000'],
 ['Sierra Leone', '5245695'],
 ['San Marino', '31477'],
 ['Senegal', '12323252'],
 ['Somalia', '10112453'],
 ['Suriname', '492829'],
 ['South Sudan', '8260490'],
 ['SÃ£o TomÃ© and PrÃ\xadncipe', '175808'],
 ['El Salvador', '6052064'],
 ['Sint Maarten', '37429'],
 ['Syria', '22198110'],
 ['Swaziland', '1354051'],
 ['Turks and Caicos Islands', '20556'],
 ['Chad', '10543464'],
 ['French Southern Territories', '140'],
 ['Togo', '6587239'],
 ['Thailand', '67089500'],
 ['Tajikistan', '7487489'],
 ['Tokelau', '1466'],
 ['East Timor', '1154625'],
 ['Turkmenistan', '4940916'],
 ['Tunisia', '10589025'],
 ['Tonga', '122580'],
 ['Turkey', '77804122'],
 ['Trinidad and Tobago', '1228691'],
 ['Tuvalu', '10472'],
 ['Taiwan', '22894384'],
 ['Tanzania', '41892895'],
 ['Ukraine', '45415596'],
 ['Uganda', '33398682'],
 ['U.S. Minor Outlying Islands', '0'],
 ['United States', '310232863'],
 ['Uruguay', '3477000'],
 ['Uzbekistan', '27865738'],
 ['Vatican City', '921'],
 ['Saint Vincent and the Grenadines', '104217'],
 ['Venezuela', '27223228'],
 ['British Virgin Islands', '21730'],
 ['U.S. Virgin Islands', '108708'],
 ['Vietnam', '89571130'],
 ['Vanuatu', '221552'],
 ['Wallis and Futuna', '16025'],
 ['Samoa', '192001'],
 ['Kosovo', '1800000'],
 ['Yemen', '23495361'],
 ['Mayotte', '159042'],
 ['South Africa', '49000000'],
 ['Zambia', '13460305'],
 ['Zimbabwe', '11651858']]

In [45]:
import pandas as pd

df = pd.DataFrame(all_countries, columns = ["Name", "Population"])

In [46]:
df

                     Name Population
0                 Andorra      84000
1    United Arab Emirates    4975593
2             Afghanistan   29121286
3     Antigua and Barbuda      86754
4                Anguilla      13254
..                    ...        ...
245                 Yemen   23495361
246               Mayotte     159042
247          South Africa   49000000
248                Zambia   13460305
249              Zimbabwe   11651858

[250 rows x 2 columns]

Navigating DOM - 
- parent
- children
- descendants
- next_sibling()
- previous_sibling()