# Pandas

In [1]:
import pandas as pd

In [2]:
info ={
    "Name":["ABC","DEF","XYZ"],
    "CGPA":[9.5,7.5,8.3]
}
df = pd.DataFrame(info)
print(df)

  Name  CGPA
0  ABC   9.5
1  DEF   7.5
2  XYZ   8.3

In [3]:
df

  Name  CGPA
0  ABC   9.5
1  DEF   7.5
2  XYZ   8.3

## Series

In [4]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

# index
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
3

In [5]:
# label -> named index (default - 0,1,2,...)
s = pd.Series([23,24,25,26],index = ["Adam","Eve","Bob","Charlie"])
print(s)

print(s["Adam"])
print(s["Bob"])

print(s.index)

# print(s[0])    # warning will come

Adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64
23
25
Index(['Adam', 'Eve', 'Bob', 'Charlie'], dtype='object')

Properties of Series ->
- Homogenous.
- Vectorized Operations.
- Handle Missing Values with NaN.
- Mutable values, immutable size.

## DataFrame

In [6]:
# Data Frame as dictionary of lists.

info = {
    "Name" : ["Adam","Eve","Bob"],
    "Age":[23,24,25],
    "CGPA":[9.5,8.4,7.6]
}

df = pd.DataFrame(info)

print(df)
print(type(df))

print(df.index)
print(df.columns)

   Name  Age  CGPA
0  Adam   23   9.5
1   Eve   24   8.4
2   Bob   25   7.6
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [7]:
df

   Name  Age  CGPA
0  Adam   23   9.5
1   Eve   24   8.4
2   Bob   25   7.6

In [8]:
# Data Frame as list of lists

df = pd.DataFrame([["Adam",23],["Bob",24],["Eve",25]], columns = ["Name","Age"])

print(df)

   Name  Age
0  Adam   23
1   Bob   24
2   Eve   25

In [9]:
# Data Frame as numpy arrays

import numpy as np
np_arr = np.array([[1,2,3],[4,5,6]])

df = pd.DataFrame(np_arr,columns = ["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

## Usage with csv and json files

In [11]:
df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>